Adding AWS Profile block to display the current `AWS_PROFILE`
yardnsm/blox-zsh-theme pull request #9
Opened 2019-05-22 15:21 UTC by dsiguero

2019-07-20 12:07 UTC, yardnsm requested changes
Sorry for the long delay, I got a lot of work lately. Anyway, looking good! Just some minor requests.

2019-07-20 12:07 UTC, yardnsm commented on README.md
> +| `BLOX_BLOCK__AWSPROFILE_COLOR` | `'orange'` | This block's color |
```suggestion
| `BLOX_BLOCK__AWSPROFILE_COLOR` | `'172' (orange)` | This block's color |
```

Reflect the actual given value

2019-07-20 12:07 UTC, yardnsm commented on blox.zsh
> +source "$__BLOX_ROOT/src/blocks/awsprofile.zsh"
Include this block after the inclusion of `virtualenv` block

2019-07-20 12:07 UTC, yardnsm commented on README.md
> +#### `awsprofile`
As this is a new block, it should be listed last.

2019-07-20 12:07 UTC, yardnsm commented on src/segments.zsh
> +__BLOX_SEG_DEFAULT__UPPER_RIGHT=( bgjobs nodejs pyenv virtualenv awsprofile )
```suggestion
__BLOX_SEG_DEFAULT__UPPER_RIGHT=( bgjobs nodejs pyenv virtualenv awsprofile time )
```

Why override the `time` block? I put it between the `virtualenv` and the `time` blocks.

2019-08-05 21:06 UTC, dsiguero commented
No worries, I can definitely relate :) please let me know if there are any other required changes.

2019-08-06 05:29 UTC, yardnsm commented
Looks great, thanks!

2019-08-06 05:30 UTC, merged